### PR TITLE
[targets.k8s] Native k8s targets support

### PR DESCRIPTION
**Pull request by manugarg**
Allow adding k8s targets without knowing about RDS.

### CODE REVIEW

**Comment by manugarg** [comment]
This implements #266.

**Comment by manugarg** [comment]
Example config:

```
probe {
    type: HTTP
    name: "http_endpoints"
    targets {
        # All endpoints that don't contain app=cloudprober label
        k8s {
            endpoints: ""
            labelSelector: "app!=cloudprober"
        }
    }
    interval: "10s"
    timeout: "5s"

    http_probe {}

    validator {
        name: "status_code_2xx"
        http_validator {
            success_status_codes: "200-499"
        }
    }
}

probe {
    type: DNS
    name: "dns_endpoints"
    targets {
        # All endpoints ending in -dns in kube-system namespace
        k8s {
            endpoints: ".*-dns"
            namespace: "kube-system"
        }
    }
    interval: "10s"
    timeout: "5s"

    dns_probe {
        resolved_domain: "www.google.com"
        min_answers: 1
        query_type: A
    }
}
```

**Comment by manugarg** [comment]
I think looking pretty good now. We just need to add some tests.

**Comment by zmailloux** [comment]
Hey @manugarg, if I'm looking at the code correctly, by default 
`        # All endpoints ending in -dns in kube-system namespace
        k8s {
            endpoints: "-dns"
            namespace: "kube-system"
        }`
Would actually include everything with "-dns" in it, whereas one would expect that ".*-dns" would be needed. This at least seems to be the case in our scenario where we are filtering on `endpoints: "server"` and it picks up endpoints with names like "dynamo-server" as well. I guess I would have expected having to define ".*server" in order to see that returned.

**Comment by zmailloux** [comment]
That makes sense! After I had wrote it I had removed it as I figured that it's intended to act as such. Makes sense, and thanks for clarifying!

**Pull request merged**
