### PR TITLE
An attempt to make YAML configs work

### PR DESCRIPTION
**Pull request by manugarg**
This is a draft PR for https://github.com/cloudprober/cloudprober/issues/178.

### CODE REVIEW

**Comment by olegmayko** [comment]
hi, are you planning to merge this?

**Comment by manugarg** [comment]
I still plan to add support for YAML configs, but it seems we won't have do it through CUE. Plans to use/support CUE are on hold right now.

**Comment by manugarg** [comment]
@olegmayko YAML config support is done: #465. But, there is no documentation right now. Here is an example file if would like to get started:
https://github.com/cloudprober/cloudprober/blob/master/config/testdata/cloudprober.yaml

**Comment by manugarg** [comment]
This is already done but in a different way. Closing this PR now.

**Comment by olegmayko** [comment]
yes, we migrated to it. thx.

**Pull request closed without merging**
